name: Build
on:
  pull_request:
  push:
    branches:
      - main
      - develop
      - hotfix/*
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Get the sources
        uses: actions/checkout@v2

      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v1

      - name: Run Cake script
        env:
          PUBLISH_STORAGE_ACCOUNT: ${{ secrets.PUBLISH_STORAGE_ACCOUNT }}
          PUBLISH_STORAGE_CONTAINER: ${{ secrets.PUBLISH_STORAGE_CONTAINER }}
          PUBLISH_STORAGE_KEY: ${{ secrets.PUBLISH_STORAGE_KEY }}
        run: |
          echo ::group::".NET NuGet Clear Cache"
          dotnet nuget locals --clear all
          echo ::endgroup::
          echo ::group::".NET Tool Restore"
          dotnet tool restore
          echo ::endgroup::
          dotnet cake